name: Build zigvulkan
run-name: ${{ gitea.actor }} is building zig vulkan 🚀
on: [push]

jobs:
  Build-Zigvulkan:
    runs-on: archlinux-base
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: zig build --summary all
      - name: Send mail
          if: failure()
          uses: https://github.com/dawidd6/action-send-mail@v3
          with:
              to: ${{ secrets.MAIL_TO }}
              from: Gitea <gitea@server>
              subject: ${{ gitea.repository }} ${{gitea.workflow}} ${{ job.status }}
              priority: high
              convert_markdown: true
              html_body: |
                  ### Job ${{ job.status }}

                  ${{ github.repository }}: [${{ github.ref }}@${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/actions)