name: Build zigvulkan
run-name: ${{ gitea.actor }} is building zig vulkan 🚀
on: [push]

jobs:
  Build-Zigvulkan:
    runs-on: riscv-ubuntu
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: zig build --summary all
      - run: zig test